setup:
	./gradlew clean installDist

build:
	./gradlew build

run-dist:
	./build/install/app/bin/app

run:
	./gradlew run

test:
	./gradlew test

check:
	./gradlew check

install:
	./gradlew installDist

clean:
	./gradlew clean

.PHONY: setup build run-dist run test check install clean
